### ISSUE TITLE
lazy pattern matching

### ISSUE THREAD

**Issue by joergen7** [rvirding/leex#1]
Hello,

I would like to usw leex in conjunction with yecc on a compiler project of mine.

I am sorry to bother you with this but I encountered a Problem, when trying to parse c-style comments, e.g.,

/* my comment */

as a Single token. The delimiters are not single characters, so a pattern like "[^"]*" as would work for strings doesn't work here.

Instead, lazy (ungreedy) pattern matching would be necessary. Unfortunately, a lazy pattern like

    /\*.*?\*/

has not worked.

I am aware, that lazy pattern matching is not a standard feature of a lexer and that I can circumvent this problem by using multiple lexers (see http://flex.sourceforge.net/manual/Why-doesn_0027t-flex-have-non_002dgreedy-operators-like-perl-does_003f.html) but it feels like I am missing something. Especially since the re package for erlang regexes supports lazy patterns (see http://www.erlang.org/doc/man/re.html and https://arifishaq.wordpress.com/2013/11/13/playing-with-regular-expressions/).

If there is any way to lex the input string in a single pass with a single lexer I would appreciate your input.

Best regards
Jörgen

**Comment by rvirding** [comment]
Typical scanner generators like lex, flex and leex generate fully deterministic scanners. This is very important as otherwise it is very easy to create a pattern which can make perl and PCRE based scanners like just re take exponential increases in time. It is their back-tracking which kills them. There is a very good paper by Rob Pike demonstrating this. 

Lazy matching is one of these properties. Leex generates fully deterministic scanners so it is actually usable. :-) Friedl in his book "Mastering Regular Expressions" in a section called "Unrolling C comments" describes how he arrived at one that works:

    /\*([^*]|\*+[^/*])*\*+/

It's not easy to comprehend. :-) I have managed to modify it to other comment patterns with a similar structure. It is the `*` in the comments which makes it harder to read. If the comments were /x ... x/ then it would be:

    /x(^x]|x+[^/x])*x+/

Robert

**Comment by joergen7** [comment]
Impressive. That helped.

Cheers
Jörgen
